### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by TotalVerb** [JuliaFinance/Roadmap#2]
It would be cool to have a logo, like some other organizations do. Maybe something made with Compose or similar!

I made one in Inkscape for Currencies.jl, designed after the generic currency symbol ¤. I'll see if I can put that on the documentation somehow.

**Comment by EricForgy** [comment]
I like it 😄

**Comment by cormullion** [comment]
For fun I made a few icons/logos. (In Julia, of course... :))

<img width="666" alt="screenshot 2019-02-09 at 09 26 57" src="https://user-images.githubusercontent.com/52289/52519043-69c2f880-2c4d-11e9-99e3-632229759d46.png">

If there's anything here you want to pursue, let me know, I'm happy to help.

**Comment by ScottPJones** [comment]
Of course, any *decent* Julia org needs a custom cormullion logo!

**Comment by EricForgy** [comment]
Some feedback...

First THANK YOU 😃 Always cool to see what you come up with @cormullion 😊 

All of them look cool.

The first logo kind of makes me think of an EKG so feels like a medical device or maybe some kind of oscilliscope 🤔 

The second and fifth logos omit currencies I care about and doesn't feel very inclusive 🤔 Would be hard to make this work and make everyone happy I think.

Forth logo looks like poker chips and the people I hope to get interested in JuliaFinance are certainly not interested in associating finance with gambling 😅 

Third logo definitely looks like an oscilloscope 😃 

I just went to bloomberg.com for inspiration and [first link](https://www.bloomberg.com/markets/commodities) took me to this:

![image](https://user-images.githubusercontent.com/8954730/52929313-e86f1280-337e-11e9-85c4-5efe3d6baf77.png)

See the circles on the chart? How would it look with three charts in Julia colors with a circle on each chart? 🤔 

The circles are usually aligned vertically like this:

![image](https://user-images.githubusercontent.com/8954730/52929429-587d9880-337f-11e9-9d6b-735bec9da520.png)

but maybe we can arrange them in a Julia triangle or something?

I dunno 😅

**Comment by EricForgy** [comment]
Or maybe some kind of pie chart like this?

![image](https://user-images.githubusercontent.com/8954730/52929720-88796b80-3380-11e9-954c-8be45e22394f.png)

That chart is not usually all green. Markets must be having a good day 😅 

We could make it filled with Julia colors?

**Comment by EricForgy** [comment]
??? 😅 

![image](https://user-images.githubusercontent.com/8954730/52934381-3a209880-3391-11e9-8d0a-cf511896cdf6.png)

**Comment by femtotrader** [comment]
What about adding a coin instead of the black circle with a motto like "In Julia we trust" ?

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52936177-64288980-3396-11e9-8961-071d82c5f541.png)

![image](https://user-images.githubusercontent.com/8954730/52936185-6c80c480-3396-11e9-89dc-5cda7a04434e.png)

![image](https://user-images.githubusercontent.com/8954730/52936199-74406900-3396-11e9-8ae3-2c52a62dc9b9.png)

![image](https://user-images.githubusercontent.com/8954730/52936225-802c2b00-3396-11e9-842b-fc38ec1a3257.png)

Of these, I'm a little partial to the last one 🤔 

First one is also ok.

Replacing the word "God" with "Julia" has connotations I'd probably prefer to avoid 😅

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52937462-1ca3fc80-339a-11e9-9cda-c1489911610d.png)

**Comment by EricForgy** [comment]
I'm taking the last one ☝️  for a test spin as the org logo. How does it look?

Font is not great. Any suggestion? 😅

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52937026-ed40c000-3398-11e9-8311-d09cc8f03f29.png)

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52937948-5cb7af00-339b-11e9-910f-6c56dc368749.png)

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52938089-ba4bfb80-339b-11e9-9200-d8c4c211e225.png)

**Comment by cormullion** [comment]
The last one of these 
https://github.com/JuliaFinance/Roadmap/issues/2#issuecomment-464625856 is the one I'd choose. I prefer logos that work without explanatory English text really, but I know it can be difficult to find graphical ideas that can't be misinterpreted (remember Slack's swastika/ducks, or AirBnB's famous logo? 😂).

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52938758-6b9f6100-339d-11e9-8daf-d341b50fce05.png)

**Comment by femtotrader** [comment]
I was thinking of a motto written around the circular part similar to a penny dollar https://en.wikipedia.org/wiki/Penny_(United_States_coin)

with year of creation of Julia (2009) or the year of its first public release (2012) and blog post https://julialang.org/blog/2012/02/why-we-created-julia

LIBERTY could be replace by the a name of a main characteristic of the language : maybe EFFECTIVENESS ?
(but that's a quite long word)

I won't write "Julia Finance" because it should be clear (without it) that it's about Finance, currencies, and be a Julia Github org (given the 3 colors)

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52938813-94275b00-339d-11e9-9905-2e415ef09776.png)

**Comment by femtotrader** [comment]
Adding a portrait of the 4 authors of the language on the coins may however require a lot of graphical talent

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52939232-95a55300-339e-11e9-8f5d-039db80d58ac.png)

**Comment by EricForgy** [comment]
![image](https://user-images.githubusercontent.com/8954730/52939392-0c425080-339f-11e9-9a77-5b21faf92a06.png)

**Comment by EricForgy** [comment]
I like this one ☝️😍

**Comment by EricForgy** [comment]
I'll use this one for now, but please feel free to present alternatives and we can always discuss 😊

**Comment by ScottPJones** [comment]
What about that, but with a rising line in black in the top (green) part, and generic coins (but not stacked), in another, and ??? in the third?

**Comment by EricForgy** [comment]
I kind of like this one as is. It is simple yet does give a "finance" feel and... as a bonus, it is a Voronoi tesselation of the Julia logo on a circle 🤓

**Comment by EricForgy** [comment]
Btw, over on Slack, with @JeffreySarnoff's help, we came up with this:

![image](https://user-images.githubusercontent.com/8954730/53011147-a75c2880-347a-11e9-861a-a74c23fa2c8f.png)

I like it 👍😊
